### ISSUE TITLE
License usage

### ISSUE THREAD

**Issue by wheelerlaw** [imazen/imageflow#127]
Looking for a simple yes/no based on my use case since it is seemingly impossible for anyone with comprehensive knowledge of the (A)GPL to be able to deliver an answer without a complete explanation of the license. I understand the concepts of and the differences between the GPL and the AGPL and just want to know if I need to publish the source of of **my** application framed in the following use case. 

Lets say I integrate the `imageflow` **executable** into my build system (the executable is downloaded onto the build system) and runs as a separate executable from the application I am trying to serve to the internet. The executable is called from a closed-source shell script with the properly configured parameters. The executable is run and generates images that will be served onto the site. Since I am calling an **exact copy** of the original work and using the output of said work (not the work itself) in my site, do I need to publish the complete source of my application?

**Comment by nathanaeljones** [comment]
> Looking for a simple yes/no

Let's be realistic... 😉 

**Image output from Imageflow is not subject to my license terms -  only those of the input data.
However, conveyance of Imageflow and interaction with Imageflow over the network must be examined**.

>  it is seemingly impossible for anyone with comprehensive knowledge of the (A)GPL to be able to deliver an answer without a complete explanation of the license. 

Yup. The AGPLv3 combines many disjoint and overlapping clauses; it's certainly hard to understand. There are many open questions, such as whether the Section 0 definition of "modified" as a catch-all term for larger works applies to "modified software" section 13, and how that interacts with section 5. 

Legal advice isn't something I can give you, but as the sole copyright holder, *I have the legal ability to grant permission and/or offer the software under any (MIT & Apache 2-compatible) terms I choose*.

**To organizations, I make the following suggestion:** *Both Imageflow and ImageResizer are available under very permissive commercial licenses. 99% of development on these projects is paid labor, which is funded via commercial license sales. So there's the option to sidestep complexity, get Apache 2-derived license terms (and support), while speeding project development.* 

----

Looking at intent, I see a few goals in the AGPL:

* Emphasis on protecting right-to-repair for end-users of a web/networked service,
* De-emphasis on link method and integration/execution model.
* Ensuring that modifications are always shared, even if binaries are not.

Despite image output not being relevance, we must consider whether Imageflow is 

  a. part of a networked service (AGPL clause 13)
  b. subject to the normal GPL conveyance considerations.  

A build server is a service that processes data (code) via the network. Furthermore, Imageflow (as the "Program") is certainly designed to interact over the network - even the executable version uses JSON and HTTP status codes.  Determining the scope of "modified version" and "covered work" becomes quite tricky.

But that determination may not be necessary.

Assuming: 
* Your build service interacts with you alone, processing only data you feed it
* You are a copyright holder for the build script providing the service, or otherwise have GPL-required rights.

**Then you are your only user, would certainly comply with my understanding of the goals of the AGPL, and I would have no reservations in granting you license to use the software in that context.**

In general, if all of those who can provide the build service images to process also have access to the build script source code, such that they can swap out Imageflow for a different version or different tool, then I would consider the right-to-repair goal is satisfied.  

As far as GPL conveyance and licensing in the context of build tools & scripts (and specifically when you must grant your own team relevant rights to a "covered work" composed of both GPL and proprietary code), I must refer you back to the Internets. It's complex, and far from a yes/no. Process boundaries are sometimes - but not always - sufficient. 

If your org is large enough for it to matter, a clear "yes" to all the things is available for a rather nominal fee.
