### ISSUE TITLE
32-bit PNG -> gif conversion has poor alpha handling

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#190]
Run the demo server, then try these: 

http://localhost:39876/demo_images/sun_256.png?format=gif
http://localhost:39876/demo_images/sun_256.png?format=jpg
![sun_256](https://user-images.githubusercontent.com/107935/42193897-85a6c61c-7e2e-11e8-9378-7e769d6618d2.png)
![sun_256](https://user-images.githubusercontent.com/107935/42193900-8752d1c2-7e2e-11e8-8da7-84c5ded6e7d9.gif)

It looks like there's no thresholding for alpha conversion (or something like that). For jpeg I can force a background color, but for GIF I think we should be able to do something smarter.

**Comment by nathanaeljones** [comment]
I'm also thinking that it may be more correct to blend the background color immediately prior to encoding. Currently this happens during image scaling (for speed), but prior to image filters being applied. Since one of those filters is alpha adjustment, the current approach doesn't fully solve the problem.
