### ISSUE TITLE
Research photograph analysis techniques for determining the best compression parameters

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow#44]
It seems like decent heuristics for determining the ideal image format should exist.

Here's a theoretical one:
1. If multi-frame, -> GIF
2. If the alpha channel is _actually_ in use, -> PNG
3. No? Why not try to compress a few randomly distributed scanlines with DEFLATE. If the ratio sucks, use JPEG, otherwise use PNG. 

Ok, using GIF?  We need to decide the color table size, and whether to preserve transparency or support animation.  We may consult the original GIF, and look at the operation graph to prove that no new colors were introduced, then re-use that table.

Using PNG? Oh, so many knobs and settings. 8-bit? 24-bit? 32-bit? Size of the color table?

JPEG? What subsampling format? What quality? Should quality decrease with resolution at a certain point (higher res usually means smaller pixels are being displayed)? Should we use trellis?

@pornel, I imagine you've thought about this quite a bit. Other than exhaustive attempts, are you aware of any good techniques for "doing the right thing" by default for the unopinionated user? We would want to budget <50ms for this, preferably <5ms for small images.

**Comment by pornel** [comment]
For PNG vs JPEG:

* It's simply images with lots of flat areas: https://yardstick.pictures/tags/img%3Apng8%20better%20than%20jpeg90 https://yardstick.pictures/tags/img%3Apng24%20better%20than%20jpeg75 so I wouldn't bother with deflate. Just count runs of pixels and maybe edges with extreme contrast.

* There's an interesting case of images that *used to be* good for PNG and were saved as JPEG. Due to artefacts it cease being good for PNG. You'd need to apply deringing first!

* For paletted PNG, if you need quality, then you'll need all 256 colors. That answers size of color table question.

GIF:

* lossy LZW will get larger if you recompress it, so don't.
* the key is to find smallest window size for each frame, and encode only deltas. 
* If you use lossy LZW to encode photo-like content then reducing number of colors doesn't actually make much difference in file size.

JPEG:

* subsampling is a good question! For fast heuristic I'd do edge/contrast detection on Cr/Cb planes, with much more weight on Cr.

**Comment by nathanaeljones** [comment]
As far as implementations for each of these codecs (and quantization itself), what you suggest for 

(a) best-in-class quality, then speed-prioritized (better: resource budgeted - for small images we can optimize more heavily) encoding.
(b) best-in-class quality, then size prioritized encoding.

I want to implement and offer both. Right now I'm using libpng 1.6.21, libjpeg-turbo 1.4.2, littlecms 2.7, and the very broken giflib 5.1.2 (replacement suggestions?).

**Comment by Pandry** [comment]
First of all, sorry for bumping this issue after such a long time, but how about the webp format?

**Comment by lilith** [comment]
Now that it's 1.0 and shipping in most major browsers, yes!
