### ISSUE TITLE
Passing a file path to the image flow context

### ISSUE THREAD

**Issue by Amraneze** [imazen/imageflow#571]
Hi @lilith,

I just have a question if **imageflow** can also accept file path instead of a buffer ? And also we are working on implementing a binding to **imageflow** with **Scala/Java** (imageflow-scala)[https://github.com/Dealermade/imageflow-scala]

Thanks!

**Comment by lilith** [comment]
I would recommend reading a file into a buffer then passing that to
imageflow. We don't expose a file path API (among other reasons) because
character sets can differ and because it wouldn't speed anything up.

Letting the binding language handle File IO also allows for async support.

Thank you so much for working on bindings for java/scala. Let me know if
you have any questions and I will try to help.

**Comment by lilith** [comment]
Also, https://github.com/imazen/imageflow-dotnet is our set of reference
bindings and is a good design to copy. The ImageJob API makes usage easy
even if you need a complex graph of operations.

**Comment by Amraneze** [comment]
Thank you @lilith for your replies.
